### ISSUE TITLE
ip: invalid argument '51820' to 'table'

### ISSUE THREAD

**Issue by Neurrone** [masipcat/wireguard-go-docker#11]
I'm getting the following error:

```
INFO: (wg0) 2020/06/02 15:11:48 Starting wireguard-go version 0.0.20200320
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.67.113.92/32 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
ip: invalid argument '51820' to 'table'
[#] resolvconf -d wg0 -f
[#] ip link delete dev wg0
```

The configure file is as follows:

```
[Interface]
PrivateKey = ...
Address = 10.67.113.92/32
DNS = 8.8.8.8

[Peer]
PublicKey = ...
AllowedIPs = 0.0.0.0/0
Endpoint = 43.245.162.234:51820
```

And here's the docker-compose:

```
version: "3.7"
services:
  wireguard:
    image: masipcat/wireguard-go:latest
    container_name: wireguard
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
    volumes:
      - ./mullvad_wireguard_linux_all_all/mullvad-au1.conf:/etc/wireguard/wg0.conf
      - /dev/net/tun:/dev/net/tun
    ports:
      - 51820:51820/udp
    restart: unless-stopped
```
